In [1]:
import numpy as np
import math

In [25]:
n,m=map(int,input().split())
mat=[]
for i in range(n):
    row= list(map(int,input().split()))
    if len(row)!=m:
        print("Column value and array length is not matched")
    mat.append(row)
a=np.array(mat)
print(a)

 2 3
 1 2 3
 4 5 6


[[1 2 3]
 [4 5 6]]


In [29]:
x=list(map(int,input().split()))
v=np.array(x)
print(v)

 1 2 3 4 5


[1 2 3 4 5]
